version: '3'
services:
  movies:
    image: summu97/projectmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: summu97/projecttrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  dth:
    image: summu97/projectdth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

  recharge:
    image: summu97/projectrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
